version: "3.9"

services:
  gallery-wall-planner:
    build: .
    container_name: gallery-web
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=8080
      - AUTHENTIK_CLIENT_ID=CLIENT_ID
      - AUTHENTIK_CLIENT_SECRET=CLIENT_SECRET
      - AUTHENTIK_AUTHORIZE_URL=https://authentik.example.com/application/o/authorize/
      - AUTHENTIK_TOKEN_URL=https://authentik.example.com/application/o/token/
      - AUTHENTIK_METADATA_URL=https://auth.example.com/application/o/application-slug/.well-known/openid-configuration
      - AUTHENTIK_REDIRECT_URI=http://localhost:5000/auth/callback
      - AUTHENTIK_SCOPE='openid email profile'
    restart: unless-stopped