version: "3.9"

services:
  gallery-wall-planner:
    build: .
    ports:
      - "${HOST_PORT:-11002}:8080"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
      - AUTHENTIK_AUTHORIZE_URL=${AUTHENTIK_AUTHORIZE_URL}
      - AUTHENTIK_TOKEN_URL=${AUTHENTIK_TOKEN_URL}
      - AUTHENTIK_METADATA_URL=${AUTHENTIK_METADATA_URL}
      - AUTHENTIK_REDIRECT_URI=${AUTHENTIK_REDIRECT_URI}
      - AUTHENTIK_SCOPE=${AUTHENTIK_SCOPE}
    restart: unless-stopped