version: "3.9"

services:
  gallery-wall-planner:
    build: .
    ports:
      - "${HOST_PORT}:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=8080