version: "3.9"

services:
  gallery-wall-planner:
    build: .
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
      - AUTHENTIK_AUTHORIZE_URL=${AUTHENTIK_AUTHORIZE_URL}
      - AUTHENTIK_TOKEN_URL=${AUTHENTIK_TOKEN_URL}
      - AUTHENTIK_METADATA_URL=${AUTHENTIK_METADATA_URL}
      - AUTHENTIK_REDIRECT_URI=${AUTHENTIK_REDIRECT_URI}
      - AUTHENTIK_SCOPE=${AUTHENTIK_SCOPE}
      # Optional MySQL support
      - DB_TYPE=${DB_TYPE:-sqlite}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      # Redis Config
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped