"""Add is_guest and session_id to User model

Revision ID: 427dec76e18d
Revises: 
Create Date: 2025-06-10 18:48:11.070104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427dec76e18d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_galleries_guest_id'), ['guest_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_id')
        batch_op.drop_column('is_guest')

    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galleries_guest_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
