"""empty message

Revision ID: 5816520d9306
Revises: 
Create Date: 2025-06-18 14:52:34.626754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5816520d9306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_guest')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('is_guest', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
