"""Remove guest_id from exhibits

Revision ID: 88577915618e
Revises: 5816520d9306
Create Date: 2025-06-18 15:54:32.089828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88577915618e'
down_revision = '5816520d9306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exhibits_guest_id'))
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_exhibits_guest_id'), ['guest_id'], unique=False)

    # ### end Alembic commands ###
