"""empty message

Revision ID: ce6f0e9b8d47
Revises: cfbf4cfdf8ad
Create Date: 2025-05-29 20:49:03.106286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6f0e9b8d47'
down_revision = 'cfbf4cfdf8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walls')
    op.drop_table('artworks')
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    op.create_table('artworks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('medium', sa.VARCHAR(length=128), nullable=True),
    sa.Column('width', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('depth', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('nfs', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('wall_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['wall_id'], ['walls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('width', sa.FLOAT(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=32), nullable=True),
    sa.Column('gallery_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
