"""empty message

Revision ID: cfbf4cfdf8ad
Revises: 
Create Date: 2025-05-29 16:17:39.663108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbf4cfdf8ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permanent_object')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permanent_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('width', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('wall_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['wall_id'], ['walls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
